name: learning_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  flutter_screenutil: ^5.8.4
  dots_indicator: ^3.0.0
  intl: ^0.19.0
  cloud_firestore: ^5.2.0
  firebase_auth: ^5.1.3
  firebase_core: ^3.3.0
  fluttertoast: ^8.2.2
  shared_preferences: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
